# Generated by Django 3.2.6 on 2021-09-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210907_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title_test',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.question'),
        ),
    ]
