# Generated by Django 3.2.6 on 2021-09-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210907_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='id пользователя')),
                ('name', models.CharField(max_length=32, verbose_name='имя пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('external_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.profile')),
                ('max_points', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maximum_points', to='polls.test')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.test')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='option_four',
            field=models.TextField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_four_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_four_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_one',
            field=models.TextField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_one_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_one_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_three',
            field=models.TextField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_three_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_three_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_two',
            field=models.TextField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_two_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_two_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
