# Generated by Django 3.2.6 on 2021-09-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210916_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='max_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maximum_pointsR', to='polls.test'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='titleR', to='polls.test'),
        ),
    ]
