# Generated by Django 3.2.6 on 2021-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210918_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='username отсутствует', max_length=32, verbose_name='имя пользователя'),
        ),
    ]
