# Generated by Django 3.2.6 on 2021-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(max_length=32, null=True, verbose_name='имя пользователя'),
        ),
    ]
